/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import info5100.university.example.Persona.EmploymentHistory.Employment;
import info5100.university.example.Persona.EmploymentHistory.EmploymentHistory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.University.University;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Surbhi
 */
public class EmploymentHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmploymentHistoryPanel
     */
    JPanel mainworkArea;
    EmploymentHistory employmentHistory;
    StudentProfile studentProfile;
    University university;
    public EmploymentHistoryPanel( JPanel mainworkArea,EmploymentHistory employmentHistory,
            StudentProfile studentProfile, 
            University university) {
        initComponents();
        this.mainworkArea = mainworkArea;
        this.employmentHistory = employmentHistory;
        this.studentProfile = studentProfile;
        this.university = university;
        refreshTable(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployment = new javax.swing.JTable();
        btnEmploymentDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Employment History");

        tblEmployment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Job Title", "Start Date", "End Date", "Employer Name"
            }
        ));
        jScrollPane1.setViewportView(tblEmployment);

        btnEmploymentDetails.setText("Employment Details");
        btnEmploymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmploymentDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnEmploymentDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEmploymentDetails)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmploymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmploymentDetailsActionPerformed
        int selectedRowIndex = tblEmployment.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(null, " Please select a row! ", 
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }  
        DefaultTableModel model = (DefaultTableModel) tblEmployment.getModel(); 
        Employment e = (Employment)model.getValueAt(selectedRowIndex, 0);
  
        EmploymentDetailsJPanel edjp = new EmploymentDetailsJPanel(mainworkArea, e, studentProfile, university);
        mainworkArea.add("EmploymentDetailsJPanel", edjp);
        CardLayout layout = (CardLayout) mainworkArea.getLayout();
        layout.next(mainworkArea);  
    }//GEN-LAST:event_btnEmploymentDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmploymentDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployment;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmployment.getModel();
        model.setRowCount(0);
        List<Employment> result =  employmentHistory.getEmployments();
        for (Employment e: result){
                Object row[] = new Object[4];
                row[0] = e;
                row[1] = e.getStartDate();
                row[2] = e.getEndDate();
                row[3] = e.getEmployerProfile().getName();
                model.addRow(row);
        }    
    }
}
