/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import info5100.university.example.Persona.Faculty.FacultyAssignment;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.reports.GPAReportData;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author swaroopgupta
 */
public class FacultyProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyProfilePanel
     */
    JPanel mainWorkArea;
    FacultyProfile facultyProfile;
    public FacultyProfilePanel(JPanel mainWorkArea,FacultyProfile facultyProfile) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.facultyProfile = facultyProfile;
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneCoursesTaught = new javax.swing.JScrollPane();
        tblCoursesTaught = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));

        TabbedPaneCoursesTaught.setEnabled(false);
        TabbedPaneCoursesTaught.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        tblCoursesTaught.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblCoursesTaught.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Course No.", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabbedPaneCoursesTaught.setViewportView(tblCoursesTaught);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TabbedPaneCoursesTaught, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(TabbedPaneCoursesTaught, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)tblCoursesTaught.getModel();
        model.setRowCount(0);
        
         for(FacultyAssignment facultyAssignment :  facultyProfile.getFacultyassignments()) {
            Object row[] = new Object[4];
            row[0] = facultyAssignment.getCourseName();
            row[1] = facultyAssignment.getCourseoffer().getCourseNumber();
            row[2] = facultyAssignment.getSemester();
            model.addRow(row);
        }   
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabbedPaneCoursesTaught;
    private javax.swing.JTable tblCoursesTaught;
    // End of variables declaration//GEN-END:variables
}
