/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import info5100.university.example.University.University;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author swaroopgupta
 */
public class SummaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryPanel
     */
    private JPanel workArea;
    University university;
    public SummaryPanel(JPanel workArea,University university) {
        initComponents();
        this.workArea = workArea;
        this.university = university;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGPAReport = new javax.swing.JButton();
        btnCourse_Internships = new javax.swing.JButton();
        btnSkillReport = new javax.swing.JButton();
        btnCourseRating = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        btnGPAReport.setText("Report for GPA v/s Industrial Success");
        btnGPAReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPAReportActionPerformed(evt);
            }
        });

        btnCourse_Internships.setText("Report of Courses vs Internships");
        btnCourse_Internships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourse_InternshipsActionPerformed(evt);
            }
        });

        btnSkillReport.setText("Skill Report");

        btnCourseRating.setText("Course Rating");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGPAReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSkillReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourse_Internships, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourseRating, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnLogout)
                .addGap(74, 74, 74)
                .addComponent(btnGPAReport)
                .addGap(42, 42, 42)
                .addComponent(btnCourse_Internships)
                .addGap(30, 30, 30)
                .addComponent(btnSkillReport)
                .addGap(37, 37, 37)
                .addComponent(btnCourseRating)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourse_InternshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourse_InternshipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourse_InternshipsActionPerformed

    private void btnGPAReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPAReportActionPerformed
        // TODO add your handling code here:
        GPA_Report gpaReport = new GPA_Report(workArea,university);
        workArea.add("GPAReport", gpaReport);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
      
    }//GEN-LAST:event_btnGPAReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginPanel loginPanel = new LoginPanel(workArea,university);
        workArea.add("LoginPanel", loginPanel);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseRating;
    private javax.swing.JButton btnCourse_Internships;
    private javax.swing.JButton btnGPAReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSkillReport;
    // End of variables declaration//GEN-END:variables
}
